# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  args:  # id of input
    description: 'Arguments to conftest. e.g. "test -p policy/k8s.rego manifests/*.yaml -o table"'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}
